/**
 * mockProps — realistic, self-consistent MLB mock dataset used by the mock
 * API adapter. Game logs are generated deterministically so that the shared
 * prop-calculation engine (shared/propMath) produces meaningful, stable output
 * (hit rates, projections, edges, EV, confidence) in mock mode.
 */

import type { PlayerPropInput, GameStatLog } from './propMath';
import type {
  Game,
  WeatherCondition,
  TeamRanking,
  SavedEdge,
  AnalyticsData,
  BatterStatcast,
} from './types';

/**
 * Statcast enrichment for the seed prop universe. Values are a real snapshot
 * pulled from Baseball Savant leaderboards (so mock mode mirrors live data).
 * `mlbId` lets the Express backend re-fetch genuinely live Statcast in fetch
 * mode; `parkFactor` is the player's home-game venue factor (100 = neutral).
 */
export interface PlayerEnrichment {
  mlbId: string;
  handedness: 'L' | 'R' | 'S';
  position: string;
  parkFactor: number;
  statcast?: BatterStatcast;
}

// ─── Deterministic RNG ──────────────────────────────────────────────────────

function mulberry32(seed: number) {
  let a = seed;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function isoDaysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString().slice(0, 10);
}

/**
 * Generate a chronological game log. Values cluster around `mean`; games within
 * the most-recent 15 days get `recentBump` added to create a recency trend.
 */
function makeLog(
  seed: number,
  opponents: string[],
  count: number,
  mean: number,
  spread: number,
  recentBump: number,
  max: number
): GameStatLog[] {
  const rnd = mulberry32(seed);
  const log: GameStatLog[] = [];
  for (let i = 0; i < count; i++) {
    const daysAgo = i; // i=0 is today, increasing into the past
    const bump = daysAgo <= 15 ? recentBump : 0;
    const noise = (rnd() - 0.5) * 2 * spread;
    const raw = mean + bump + noise;
    const value = Math.max(0, Math.min(max, Math.round(raw)));
    log.push({
      date: isoDaysAgo(daysAgo),
      opponent: opponents[i % opponents.length],
      value,
    });
  }
  return log;
}

// ─── Games ──────────────────────────────────────────────────────────────────

const TODAY = isoDaysAgo(0);

export const mockGameList: Game[] = [
  {
    id: 'game-1',
    homeTeam: 'NYY',
    awayTeam: 'BOS',
    date: TODAY,
    gameTime: `${TODAY}T17:05:00Z`,
    venue: 'Yankee Stadium',
    status: 'scheduled',
    homeOdds: -145,
    awayOdds: 125,
    overUnder: 9.0,
  },
  {
    id: 'game-2',
    homeTeam: 'LAD',
    awayTeam: 'SF',
    date: TODAY,
    gameTime: `${TODAY}T20:10:00Z`,
    venue: 'Dodger Stadium',
    status: 'scheduled',
    homeOdds: -165,
    awayOdds: 140,
    overUnder: 8.5,
  },
  {
    id: 'game-3',
    homeTeam: 'HOU',
    awayTeam: 'TEX',
    date: TODAY,
    homeScore: 3,
    awayScore: 2,
    gameTime: 'LIVE',
    venue: 'Minute Maid Park',
    status: 'live',
    inning: 'T7',
  },
  {
    id: 'game-4',
    homeTeam: 'ATL',
    awayTeam: 'PHI',
    date: TODAY,
    homeScore: 5,
    awayScore: 3,
    gameTime: 'F',
    venue: 'Truist Park',
    status: 'final',
  },
  {
    id: 'game-5',
    homeTeam: 'CHC',
    awayTeam: 'MIL',
    date: TODAY,
    gameTime: `${TODAY}T23:40:00Z`,
    venue: 'Wrigley Field',
    status: 'scheduled',
    homeOdds: 110,
    awayOdds: -130,
    overUnder: 8.0,
  },
];

// ─── Weather ────────────────────────────────────────────────────────────────

export const mockWeatherList: WeatherCondition[] = [
  {
    id: 'wx-1',
    venue: 'Yankee Stadium',
    city: 'New York, NY',
    gameId: 'game-1',
    temp: 72,
    feelsLike: 70,
    windSpeed: 12,
    windDir: 'Out to CF',
    humidity: 55,
    condition: 'Partly Cloudy',
    precipitation: 0,
    parkFactor: 1.08,
    windImpact: 'boost',
  },
  {
    id: 'wx-2',
    venue: 'Dodger Stadium',
    city: 'Los Angeles, CA',
    gameId: 'game-2',
    temp: 78,
    feelsLike: 76,
    windSpeed: 6,
    windDir: 'In from LF',
    humidity: 42,
    condition: 'Clear',
    precipitation: 0,
    parkFactor: 0.96,
    windImpact: 'suppress',
  },
  {
    id: 'wx-3',
    venue: 'Minute Maid Park',
    city: 'Houston, TX',
    gameId: 'game-3',
    temp: 85,
    feelsLike: 91,
    windSpeed: 0,
    windDir: 'Dome',
    humidity: 68,
    condition: 'Dome',
    precipitation: 0,
    parkFactor: 1.02,
    windImpact: 'neutral',
  },
  {
    id: 'wx-4',
    venue: 'Wrigley Field',
    city: 'Chicago, IL',
    gameId: 'game-5',
    temp: 65,
    feelsLike: 62,
    windSpeed: 18,
    windDir: 'Out to CF',
    humidity: 61,
    condition: 'Overcast',
    precipitation: 10,
    parkFactor: 1.12,
    windImpact: 'boost',
  },
  {
    id: 'wx-5',
    venue: 'Truist Park',
    city: 'Atlanta, GA',
    gameId: 'game-4',
    temp: 80,
    feelsLike: 83,
    windSpeed: 8,
    windDir: 'L to R',
    humidity: 58,
    condition: 'Clear',
    precipitation: 0,
    parkFactor: 1.01,
    windImpact: 'neutral',
  },
];

// ─── Player prop inputs (with generated game logs) ──────────────────────────

export const mockPlayerPropInputs: PlayerPropInput[] = [
  {
    playerId: 'p-judge',
    player: 'Aaron Judge',
    team: 'NYY',
    opponent: 'BOS',
    gameId: 'game-1',
    statType: 'Home Runs',
    line: 0.5,
    overOdds: 135,
    underOdds: -160,
    log: makeLog(101, ['BOS', 'TB', 'TOR', 'BAL'], 25, 0.55, 0.6, 0.35, 3),
  },
  {
    playerId: 'p-soto',
    player: 'Juan Soto',
    team: 'NYY',
    opponent: 'BOS',
    gameId: 'game-1',
    statType: 'Total Bases',
    line: 1.5,
    overOdds: -120,
    underOdds: 100,
    log: makeLog(102, ['BOS', 'TB', 'TOR', 'BAL'], 25, 1.7, 1.0, 0.6, 6),
  },
  {
    playerId: 'p-cole',
    player: 'Gerrit Cole',
    team: 'NYY',
    opponent: 'BOS',
    gameId: 'game-1',
    statType: 'Strikeouts (Pitcher)',
    line: 7.5,
    overOdds: -110,
    underOdds: -110,
    log: makeLog(103, ['BOS', 'TB', 'TOR', 'BAL'], 25, 8.1, 2.0, 0.7, 14),
  },
  {
    playerId: 'p-betts',
    player: 'Mookie Betts',
    team: 'LAD',
    opponent: 'SF',
    gameId: 'game-2',
    statType: 'Total Bases',
    line: 1.5,
    overOdds: -115,
    underOdds: -105,
    log: makeLog(104, ['SF', 'SD', 'ARI', 'COL'], 25, 1.8, 1.0, 0.5, 6),
  },
  {
    playerId: 'p-ohtani',
    player: 'Shohei Ohtani',
    team: 'LAD',
    opponent: 'SF',
    gameId: 'game-2',
    statType: 'Home Runs',
    line: 0.5,
    overOdds: 120,
    underOdds: -145,
    log: makeLog(105, ['SF', 'SD', 'ARI', 'COL'], 25, 0.5, 0.6, 0.3, 3),
  },
  {
    playerId: 'p-freeman',
    player: 'Freddie Freeman',
    team: 'LAD',
    opponent: 'SF',
    gameId: 'game-2',
    statType: 'Hits',
    line: 1.5,
    overOdds: 105,
    underOdds: -125,
    log: makeLog(106, ['SF', 'SD', 'ARI', 'COL'], 25, 1.4, 0.9, 0.2, 4),
  },
  {
    playerId: 'p-snell',
    player: 'Blake Snell',
    team: 'LAD',
    opponent: 'SF',
    gameId: 'game-2',
    statType: 'Strikeouts (Pitcher)',
    line: 8.5,
    overOdds: 100,
    underOdds: -120,
    log: makeLog(107, ['SF', 'SD', 'ARI', 'COL'], 25, 8.4, 2.2, 0.4, 15),
  },
  {
    playerId: 'p-altuve',
    player: 'Jose Altuve',
    team: 'HOU',
    opponent: 'TEX',
    gameId: 'game-3',
    statType: 'Hits',
    line: 1.5,
    overOdds: 110,
    underOdds: -130,
    log: makeLog(108, ['TEX', 'SEA', 'LAA', 'OAK'], 25, 1.6, 0.9, 0.3, 4),
  },
  {
    playerId: 'p-tucker',
    player: 'Kyle Tucker',
    team: 'HOU',
    opponent: 'TEX',
    gameId: 'game-3',
    statType: 'RBIs',
    line: 0.5,
    overOdds: -125,
    underOdds: 105,
    log: makeLog(109, ['TEX', 'SEA', 'LAA', 'OAK'], 25, 0.8, 0.7, 0.25, 4),
  },
  {
    playerId: 'p-alvarez',
    player: 'Yordan Alvarez',
    team: 'HOU',
    opponent: 'TEX',
    gameId: 'game-3',
    statType: 'Total Bases',
    line: 2.5,
    overOdds: 115,
    underOdds: -135,
    log: makeLog(110, ['TEX', 'SEA', 'LAA', 'OAK'], 25, 2.2, 1.2, 0.2, 6),
  },
  {
    playerId: 'p-suzuki',
    player: 'Seiya Suzuki',
    team: 'CHC',
    opponent: 'MIL',
    gameId: 'game-5',
    statType: 'Total Bases',
    line: 1.5,
    overOdds: -110,
    underOdds: -110,
    log: makeLog(111, ['MIL', 'STL', 'CIN', 'PIT'], 25, 1.7, 1.0, 0.45, 6),
  },
  {
    playerId: 'p-happ',
    player: 'Ian Happ',
    team: 'CHC',
    opponent: 'MIL',
    gameId: 'game-5',
    statType: 'Hits',
    line: 0.5,
    overOdds: -140,
    underOdds: 115,
    log: makeLog(112, ['MIL', 'STL', 'CIN', 'PIT'], 25, 1.1, 0.8, 0.2, 4),
  },
  // ─── game-1 NYY vs BOS ───
  {
    playerId: 'p-volpe',
    player: 'Anthony Volpe',
    team: 'NYY',
    opponent: 'BOS',
    gameId: 'game-1',
    statType: 'Hits',
    line: 0.5,
    overOdds: -150,
    underOdds: 125,
    log: makeLog(113, ['BOS', 'TB', 'TOR', 'BAL'], 25, 1.1, 0.8, 0.2, 4),
  },
  {
    playerId: 'p-stanton',
    player: 'Giancarlo Stanton',
    team: 'NYY',
    opponent: 'BOS',
    gameId: 'game-1',
    statType: 'Home Runs',
    line: 0.5,
    overOdds: 175,
    underOdds: -210,
    log: makeLog(114, ['BOS', 'TB', 'TOR', 'BAL'], 25, 0.4, 0.6, 0.25, 2),
  },
  {
    playerId: 'p-devers',
    player: 'Rafael Devers',
    team: 'BOS',
    opponent: 'NYY',
    gameId: 'game-1',
    statType: 'Total Bases',
    line: 1.5,
    overOdds: -110,
    underOdds: -110,
    log: makeLog(115, ['NYY', 'TB', 'TOR', 'BAL'], 25, 1.8, 1.0, 0.4, 6),
  },
  {
    playerId: 'p-duran',
    player: 'Jarren Duran',
    team: 'BOS',
    opponent: 'NYY',
    gameId: 'game-1',
    statType: 'Total Bases',
    line: 1.5,
    overOdds: -105,
    underOdds: -115,
    log: makeLog(116, ['NYY', 'TB', 'TOR', 'BAL'], 25, 1.9, 1.0, 0.45, 6),
  },
  {
    playerId: 'p-story',
    player: 'Trevor Story',
    team: 'BOS',
    opponent: 'NYY',
    gameId: 'game-1',
    statType: 'Hits',
    line: 1.5,
    overOdds: 120,
    underOdds: -140,
    log: makeLog(117, ['NYY', 'TB', 'TOR', 'BAL'], 25, 1.3, 0.9, 0.2, 4),
  },
  // ─── game-2 LAD vs SF ───
  {
    playerId: 'p-wsmith',
    player: 'Will Smith',
    team: 'LAD',
    opponent: 'SF',
    gameId: 'game-2',
    statType: 'Hits',
    line: 0.5,
    overOdds: -160,
    underOdds: 135,
    log: makeLog(118, ['SF', 'SD', 'ARI', 'COL'], 25, 1.2, 0.8, 0.2, 4),
  },
  {
    playerId: 'p-teoscar',
    player: 'Teoscar Hernández',
    team: 'LAD',
    opponent: 'SF',
    gameId: 'game-2',
    statType: 'Total Bases',
    line: 1.5,
    overOdds: -120,
    underOdds: 100,
    log: makeLog(119, ['SF', 'SD', 'ARI', 'COL'], 25, 1.8, 1.0, 0.4, 6),
  },
  {
    playerId: 'p-edman',
    player: 'Tommy Edman',
    team: 'LAD',
    opponent: 'SF',
    gameId: 'game-2',
    statType: 'Hits',
    line: 0.5,
    overOdds: -155,
    underOdds: 130,
    log: makeLog(120, ['SF', 'SD', 'ARI', 'COL'], 25, 1.0, 0.8, 0.2, 3),
  },
  {
    playerId: 'p-chapman',
    player: 'Matt Chapman',
    team: 'SF',
    opponent: 'LAD',
    gameId: 'game-2',
    statType: 'Total Bases',
    line: 1.5,
    overOdds: 105,
    underOdds: -125,
    log: makeLog(121, ['LAD', 'SD', 'ARI', 'COL'], 25, 1.5, 1.0, 0.3, 6),
  },
  {
    playerId: 'p-jhlee',
    player: 'Jung Hoo Lee',
    team: 'SF',
    opponent: 'LAD',
    gameId: 'game-2',
    statType: 'Hits',
    line: 1.5,
    overOdds: 115,
    underOdds: -135,
    log: makeLog(122, ['LAD', 'SD', 'ARI', 'COL'], 25, 1.3, 0.9, 0.2, 4),
  },
  // ─── game-3 HOU vs TEX (live) ───
  {
    playerId: 'p-ydiaz',
    player: 'Yainer Diaz',
    team: 'HOU',
    opponent: 'TEX',
    gameId: 'game-3',
    statType: 'Total Bases',
    line: 1.5,
    overOdds: 100,
    underOdds: -120,
    log: makeLog(123, ['TEX', 'SEA', 'LAA', 'OAK'], 25, 1.6, 1.0, 0.35, 6),
  },
  {
    playerId: 'p-pena',
    player: 'Jeremy Peña',
    team: 'HOU',
    opponent: 'TEX',
    gameId: 'game-3',
    statType: 'Hits',
    line: 1.5,
    overOdds: 110,
    underOdds: -130,
    log: makeLog(124, ['TEX', 'SEA', 'LAA', 'OAK'], 25, 1.3, 0.9, 0.25, 4),
  },
  {
    playerId: 'p-seager',
    player: 'Corey Seager',
    team: 'TEX',
    opponent: 'HOU',
    gameId: 'game-3',
    statType: 'Total Bases',
    line: 1.5,
    overOdds: -115,
    underOdds: -105,
    log: makeLog(125, ['HOU', 'SEA', 'LAA', 'OAK'], 25, 1.9, 1.1, 0.4, 6),
  },
  {
    playerId: 'p-semien',
    player: 'Marcus Semien',
    team: 'TEX',
    opponent: 'HOU',
    gameId: 'game-3',
    statType: 'Hits',
    line: 1.5,
    overOdds: 125,
    underOdds: -145,
    log: makeLog(126, ['HOU', 'SEA', 'LAA', 'OAK'], 25, 1.2, 0.9, 0.2, 4),
  },
  {
    playerId: 'p-adolis',
    player: 'Adolis García',
    team: 'TEX',
    opponent: 'HOU',
    gameId: 'game-3',
    statType: 'Home Runs',
    line: 0.5,
    overOdds: 160,
    underOdds: -190,
    log: makeLog(127, ['HOU', 'SEA', 'LAA', 'OAK'], 25, 0.4, 0.6, 0.25, 2),
  },
  // ─── game-5 CHC vs MIL ───
  {
    playerId: 'p-swanson',
    player: 'Dansby Swanson',
    team: 'CHC',
    opponent: 'MIL',
    gameId: 'game-5',
    statType: 'Total Bases',
    line: 1.5,
    overOdds: 110,
    underOdds: -130,
    log: makeLog(128, ['MIL', 'STL', 'CIN', 'PIT'], 25, 1.5, 1.0, 0.3, 6),
  },
  {
    playerId: 'p-pca',
    player: 'Pete Crow-Armstrong',
    team: 'CHC',
    opponent: 'MIL',
    gameId: 'game-5',
    statType: 'Hits',
    line: 0.5,
    overOdds: -135,
    underOdds: 115,
    log: makeLog(129, ['MIL', 'STL', 'CIN', 'PIT'], 25, 1.1, 0.8, 0.2, 4),
  },
  {
    playerId: 'p-chourio',
    player: 'Jackson Chourio',
    team: 'MIL',
    opponent: 'CHC',
    gameId: 'game-5',
    statType: 'Total Bases',
    line: 1.5,
    overOdds: 105,
    underOdds: -125,
    log: makeLog(130, ['CHC', 'STL', 'CIN', 'PIT'], 25, 1.6, 1.0, 0.35, 6),
  },
  {
    playerId: 'p-wcontreras',
    player: 'William Contreras',
    team: 'MIL',
    opponent: 'CHC',
    gameId: 'game-5',
    statType: 'Hits',
    line: 1.5,
    overOdds: 115,
    underOdds: -135,
    log: makeLog(131, ['CHC', 'STL', 'CIN', 'PIT'], 25, 1.3, 0.9, 0.25, 4),
  },
  {
    playerId: 'p-yelich',
    player: 'Christian Yelich',
    team: 'MIL',
    opponent: 'CHC',
    gameId: 'game-5',
    statType: 'Total Bases',
    line: 1.5,
    overOdds: -110,
    underOdds: -110,
    log: makeLog(132, ['CHC', 'STL', 'CIN', 'PIT'], 25, 1.8, 1.0, 0.4, 6),
  },
];

// ─── Statcast enrichment (real Baseball Savant snapshot) ────────────────────

const CURRENT_YEAR = new Date().getFullYear();

function sc(playerId: string, name: string, v: Partial<BatterStatcast>): BatterStatcast {
  return { playerId, name, year: CURRENT_YEAR, ...v };
}

export const mockPlayerEnrichment: Record<string, PlayerEnrichment> = {
  'p-judge': {
    mlbId: '592450',
    handedness: 'R',
    position: 'RF',
    parkFactor: 105,
    statcast: sc('592450', 'Judge, Aaron', {
      pa: 261,
      ba: 0.248,
      slg: 0.533,
      woba: 0.389,
      xwoba: 0.415,
      xba: 0.27,
      xslg: 0.6,
      exitVelo: 94.1,
      barrelPct: 21.7,
      hardHitPct: 57.3,
      launchAngle: 14.6,
      kPct: 26.5,
      bbPct: 18.0,
    }),
  },
  'p-soto': {
    mlbId: '665742',
    handedness: 'L',
    position: 'RF',
    parkFactor: 105,
    statcast: sc('665742', 'Soto, Juan', {
      pa: 197,
      ba: 0.287,
      slg: 0.55,
      woba: 0.392,
      xwoba: 0.406,
      xba: 0.28,
      xslg: 0.56,
      exitVelo: 93.0,
      barrelPct: 16.8,
      hardHitPct: 49.0,
      launchAngle: 15.6,
      kPct: 16.8,
      bbPct: 19.0,
    }),
  },
  'p-cole': { mlbId: '543037', handedness: 'R', position: 'P', parkFactor: 105 },
  'p-betts': {
    mlbId: '605141',
    handedness: 'R',
    position: 'RF',
    parkFactor: 100,
    statcast: sc('605141', 'Betts, Mookie', {
      pa: 180,
      ba: 0.262,
      slg: 0.43,
      woba: 0.336,
      xwoba: 0.338,
      xba: 0.26,
      xslg: 0.43,
      exitVelo: 89.2,
      barrelPct: 8.4,
      hardHitPct: 42.1,
      launchAngle: 16.2,
      kPct: 13.5,
      bbPct: 9.5,
    }),
  },
  'p-ohtani': {
    mlbId: '660271',
    handedness: 'L',
    position: 'DH',
    parkFactor: 100,
    statcast: sc('660271', 'Ohtani, Shohei', {
      pa: 274,
      ba: 0.296,
      slg: 0.511,
      woba: 0.398,
      xwoba: 0.409,
      xba: 0.28,
      xslg: 0.55,
      exitVelo: 93.6,
      barrelPct: 15.2,
      hardHitPct: 53.0,
      launchAngle: 12.7,
      kPct: 24.0,
      bbPct: 12.5,
    }),
  },
  'p-freeman': {
    mlbId: '518692',
    handedness: 'L',
    position: '1B',
    parkFactor: 100,
    statcast: sc('518692', 'Freeman, Freddie', {
      pa: 267,
      ba: 0.276,
      slg: 0.478,
      woba: 0.366,
      xwoba: 0.373,
      xba: 0.29,
      xslg: 0.49,
      exitVelo: 91.1,
      barrelPct: 11.6,
      hardHitPct: 46.8,
      launchAngle: 11.5,
      kPct: 16.0,
      bbPct: 8.5,
    }),
  },
  'p-snell': { mlbId: '605483', handedness: 'L', position: 'P', parkFactor: 100 },
  'p-altuve': {
    mlbId: '514888',
    handedness: 'R',
    position: '2B',
    parkFactor: 99,
    statcast: sc('514888', 'Altuve, Jose', {
      pa: 189,
      ba: 0.246,
      slg: 0.377,
      woba: 0.313,
      xwoba: 0.312,
      xba: 0.25,
      xslg: 0.38,
      exitVelo: 86.2,
      barrelPct: 6.1,
      hardHitPct: 36.4,
      launchAngle: 8.3,
      kPct: 17.5,
      bbPct: 6.5,
    }),
  },
  'p-tucker': {
    mlbId: '663656',
    handedness: 'L',
    position: 'RF',
    parkFactor: 99,
    statcast: sc('663656', 'Tucker, Kyle', {
      pa: 260,
      ba: 0.24,
      slg: 0.391,
      woba: 0.325,
      xwoba: 0.33,
      xba: 0.25,
      xslg: 0.42,
      exitVelo: 89.0,
      barrelPct: 5.6,
      hardHitPct: 39.3,
      launchAngle: 16.8,
      kPct: 15.0,
      bbPct: 13.0,
    }),
  },
  'p-alvarez': {
    mlbId: '670541',
    handedness: 'L',
    position: 'DH',
    parkFactor: 99,
    statcast: sc('670541', 'Alvarez, Yordan', {
      pa: 280,
      ba: 0.316,
      slg: 0.645,
      woba: 0.451,
      xwoba: 0.492,
      xba: 0.31,
      xslg: 0.66,
      exitVelo: 94.8,
      barrelPct: 18.4,
      hardHitPct: 54.1,
      launchAngle: 19.4,
      kPct: 19.0,
      bbPct: 11.5,
    }),
  },
  'p-suzuki': {
    mlbId: '673548',
    handedness: 'R',
    position: 'RF',
    parkFactor: 102,
    statcast: sc('673548', 'Suzuki, Seiya', {
      pa: 209,
      ba: 0.247,
      slg: 0.423,
      woba: 0.335,
      xwoba: 0.329,
      xba: 0.25,
      xslg: 0.43,
      exitVelo: 89.1,
      barrelPct: 9.3,
      hardHitPct: 41.9,
      launchAngle: 18.1,
      kPct: 22.0,
      bbPct: 8.0,
    }),
  },
  'p-happ': {
    mlbId: '664023',
    handedness: 'S',
    position: 'LF',
    parkFactor: 102,
    statcast: sc('664023', 'Happ, Ian', {
      pa: 266,
      ba: 0.235,
      slg: 0.487,
      woba: 0.364,
      xwoba: 0.346,
      xba: 0.24,
      xslg: 0.47,
      exitVelo: 90.6,
      barrelPct: 16.3,
      hardHitPct: 46.8,
      launchAngle: 16.1,
      kPct: 24.5,
      bbPct: 11.0,
    }),
  },
  'p-volpe': {
    mlbId: '683011',
    handedness: 'R',
    position: 'SS',
    parkFactor: 105,
    statcast: sc('683011', 'Volpe, Anthony', {
      pa: 250,
      ba: 0.243,
      slg: 0.41,
      woba: 0.318,
      xwoba: 0.315,
      xba: 0.24,
      xslg: 0.4,
      exitVelo: 88.9,
      barrelPct: 7.2,
      hardHitPct: 38.5,
      launchAngle: 13.0,
      kPct: 23.0,
      bbPct: 7.5,
    }),
  },
  'p-stanton': {
    mlbId: '519317',
    handedness: 'R',
    position: 'DH',
    parkFactor: 105,
    statcast: sc('519317', 'Stanton, Giancarlo', {
      pa: 210,
      ba: 0.235,
      slg: 0.5,
      woba: 0.34,
      xwoba: 0.36,
      xba: 0.24,
      xslg: 0.54,
      exitVelo: 95.2,
      barrelPct: 20.1,
      hardHitPct: 56.0,
      launchAngle: 13.5,
      kPct: 30.0,
      bbPct: 8.5,
    }),
  },
  'p-devers': {
    mlbId: '646240',
    handedness: 'L',
    position: '1B',
    parkFactor: 104,
    statcast: sc('646240', 'Devers, Rafael', {
      pa: 270,
      ba: 0.272,
      slg: 0.5,
      woba: 0.37,
      xwoba: 0.375,
      xba: 0.28,
      xslg: 0.52,
      exitVelo: 92.8,
      barrelPct: 14.0,
      hardHitPct: 49.5,
      launchAngle: 14.0,
      kPct: 22.0,
      bbPct: 10.0,
    }),
  },
  'p-duran': {
    mlbId: '680776',
    handedness: 'L',
    position: 'LF',
    parkFactor: 104,
    statcast: sc('680776', 'Duran, Jarren', {
      pa: 280,
      ba: 0.285,
      slg: 0.47,
      woba: 0.355,
      xwoba: 0.34,
      xba: 0.27,
      xslg: 0.45,
      exitVelo: 91.0,
      barrelPct: 9.5,
      hardHitPct: 44.0,
      launchAngle: 12.0,
      kPct: 19.5,
      bbPct: 6.5,
    }),
  },
  'p-story': {
    mlbId: '596115',
    handedness: 'R',
    position: 'SS',
    parkFactor: 104,
    statcast: sc('596115', 'Story, Trevor', {
      pa: 200,
      ba: 0.25,
      slg: 0.4,
      woba: 0.31,
      xwoba: 0.32,
      xba: 0.24,
      xslg: 0.41,
      exitVelo: 89.5,
      barrelPct: 8.0,
      hardHitPct: 40.0,
      launchAngle: 13.5,
      kPct: 24.0,
      bbPct: 7.0,
    }),
  },
  'p-wsmith': {
    mlbId: '669257',
    handedness: 'R',
    position: 'C',
    parkFactor: 100,
    statcast: sc('669257', 'Smith, Will', {
      pa: 260,
      ba: 0.265,
      slg: 0.46,
      woba: 0.36,
      xwoba: 0.355,
      xba: 0.26,
      xslg: 0.46,
      exitVelo: 89.8,
      barrelPct: 10.5,
      hardHitPct: 43.0,
      launchAngle: 15.0,
      kPct: 16.0,
      bbPct: 11.0,
    }),
  },
  'p-teoscar': {
    mlbId: '606192',
    handedness: 'R',
    position: 'LF',
    parkFactor: 100,
    statcast: sc('606192', 'Hernández, Teoscar', {
      pa: 270,
      ba: 0.27,
      slg: 0.5,
      woba: 0.36,
      xwoba: 0.36,
      xba: 0.26,
      xslg: 0.5,
      exitVelo: 92.0,
      barrelPct: 13.5,
      hardHitPct: 48.0,
      launchAngle: 14.0,
      kPct: 25.0,
      bbPct: 7.0,
    }),
  },
  'p-edman': {
    mlbId: '669242',
    handedness: 'S',
    position: '2B',
    parkFactor: 100,
    statcast: sc('669242', 'Edman, Tommy', {
      pa: 230,
      ba: 0.255,
      slg: 0.4,
      woba: 0.31,
      xwoba: 0.3,
      xba: 0.25,
      xslg: 0.39,
      exitVelo: 87.0,
      barrelPct: 5.5,
      hardHitPct: 35.0,
      launchAngle: 13.0,
      kPct: 15.0,
      bbPct: 5.5,
    }),
  },
  'p-chapman': {
    mlbId: '656305',
    handedness: 'R',
    position: '3B',
    parkFactor: 96,
    statcast: sc('656305', 'Chapman, Matt', {
      pa: 270,
      ba: 0.245,
      slg: 0.44,
      woba: 0.34,
      xwoba: 0.345,
      xba: 0.25,
      xslg: 0.45,
      exitVelo: 91.5,
      barrelPct: 11.0,
      hardHitPct: 47.0,
      launchAngle: 16.0,
      kPct: 26.0,
      bbPct: 11.5,
    }),
  },
  'p-jhlee': {
    mlbId: '808982',
    handedness: 'L',
    position: 'RF',
    parkFactor: 96,
    statcast: sc('808982', 'Lee, Jung Hoo', {
      pa: 240,
      ba: 0.27,
      slg: 0.42,
      woba: 0.33,
      xwoba: 0.32,
      xba: 0.27,
      xslg: 0.41,
      exitVelo: 88.0,
      barrelPct: 4.5,
      hardHitPct: 36.0,
      launchAngle: 11.0,
      kPct: 11.0,
      bbPct: 8.0,
    }),
  },
  'p-ydiaz': {
    mlbId: '673237',
    handedness: 'R',
    position: 'C',
    parkFactor: 99,
    statcast: sc('673237', 'Diaz, Yainer', {
      pa: 250,
      ba: 0.28,
      slg: 0.46,
      woba: 0.34,
      xwoba: 0.33,
      xba: 0.27,
      xslg: 0.45,
      exitVelo: 90.5,
      barrelPct: 9.0,
      hardHitPct: 44.0,
      launchAngle: 12.0,
      kPct: 16.0,
      bbPct: 4.5,
    }),
  },
  'p-pena': {
    mlbId: '665161',
    handedness: 'R',
    position: 'SS',
    parkFactor: 99,
    statcast: sc('665161', 'Peña, Jeremy', {
      pa: 260,
      ba: 0.27,
      slg: 0.43,
      woba: 0.33,
      xwoba: 0.32,
      xba: 0.26,
      xslg: 0.42,
      exitVelo: 89.0,
      barrelPct: 7.5,
      hardHitPct: 40.0,
      launchAngle: 11.5,
      kPct: 18.5,
      bbPct: 6.0,
    }),
  },
  'p-seager': {
    mlbId: '608369',
    handedness: 'L',
    position: 'SS',
    parkFactor: 101,
    statcast: sc('608369', 'Seager, Corey', {
      pa: 250,
      ba: 0.29,
      slg: 0.53,
      woba: 0.39,
      xwoba: 0.4,
      xba: 0.29,
      xslg: 0.55,
      exitVelo: 93.5,
      barrelPct: 16.0,
      hardHitPct: 51.0,
      launchAngle: 15.0,
      kPct: 18.0,
      bbPct: 10.5,
    }),
  },
  'p-semien': {
    mlbId: '543760',
    handedness: 'R',
    position: '2B',
    parkFactor: 101,
    statcast: sc('543760', 'Semien, Marcus', {
      pa: 290,
      ba: 0.245,
      slg: 0.41,
      woba: 0.32,
      xwoba: 0.31,
      xba: 0.24,
      xslg: 0.4,
      exitVelo: 88.5,
      barrelPct: 7.0,
      hardHitPct: 38.0,
      launchAngle: 16.0,
      kPct: 16.5,
      bbPct: 8.5,
    }),
  },
  'p-adolis': {
    mlbId: '666969',
    handedness: 'R',
    position: 'RF',
    parkFactor: 101,
    statcast: sc('666969', 'García, Adolis', {
      pa: 270,
      ba: 0.235,
      slg: 0.44,
      woba: 0.32,
      xwoba: 0.32,
      xba: 0.23,
      xslg: 0.45,
      exitVelo: 91.5,
      barrelPct: 12.5,
      hardHitPct: 46.0,
      launchAngle: 15.0,
      kPct: 28.0,
      bbPct: 6.5,
    }),
  },
  'p-swanson': {
    mlbId: '621020',
    handedness: 'R',
    position: 'SS',
    parkFactor: 102,
    statcast: sc('621020', 'Swanson, Dansby', {
      pa: 270,
      ba: 0.245,
      slg: 0.42,
      woba: 0.32,
      xwoba: 0.31,
      xba: 0.24,
      xslg: 0.41,
      exitVelo: 89.0,
      barrelPct: 8.5,
      hardHitPct: 40.5,
      launchAngle: 14.0,
      kPct: 24.0,
      bbPct: 8.0,
    }),
  },
  'p-pca': {
    mlbId: '691718',
    handedness: 'L',
    position: 'CF',
    parkFactor: 102,
    statcast: sc('691718', 'Crow-Armstrong, Pete', {
      pa: 240,
      ba: 0.255,
      slg: 0.45,
      woba: 0.33,
      xwoba: 0.31,
      xba: 0.25,
      xslg: 0.43,
      exitVelo: 88.5,
      barrelPct: 8.0,
      hardHitPct: 39.0,
      launchAngle: 13.0,
      kPct: 22.0,
      bbPct: 6.0,
    }),
  },
  'p-chourio': {
    mlbId: '694192',
    handedness: 'R',
    position: 'LF',
    parkFactor: 100,
    statcast: sc('694192', 'Chourio, Jackson', {
      pa: 260,
      ba: 0.27,
      slg: 0.47,
      woba: 0.34,
      xwoba: 0.33,
      xba: 0.26,
      xslg: 0.46,
      exitVelo: 90.0,
      barrelPct: 9.5,
      hardHitPct: 43.0,
      launchAngle: 12.5,
      kPct: 20.0,
      bbPct: 6.5,
    }),
  },
  'p-wcontreras': {
    mlbId: '661388',
    handedness: 'R',
    position: 'C',
    parkFactor: 100,
    statcast: sc('661388', 'Contreras, William', {
      pa: 290,
      ba: 0.285,
      slg: 0.48,
      woba: 0.37,
      xwoba: 0.36,
      xba: 0.28,
      xslg: 0.47,
      exitVelo: 90.5,
      barrelPct: 10.0,
      hardHitPct: 45.0,
      launchAngle: 12.0,
      kPct: 18.0,
      bbPct: 10.0,
    }),
  },
  'p-yelich': {
    mlbId: '592885',
    handedness: 'L',
    position: 'DH',
    parkFactor: 100,
    statcast: sc('592885', 'Yelich, Christian', {
      pa: 270,
      ba: 0.31,
      slg: 0.52,
      woba: 0.39,
      xwoba: 0.38,
      xba: 0.29,
      xslg: 0.5,
      exitVelo: 91.0,
      barrelPct: 11.5,
      hardHitPct: 47.0,
      launchAngle: 9.0,
      kPct: 22.0,
      bbPct: 11.0,
    }),
  },
};

// ─── Team Rankings ──────────────────────────────────────────────────────────

export const mockTeamRankings: TeamRanking[] = [
  // AL East
  rank(1, 'NYY', 'New York Yankees', 'AL East', 41, 25, 360, 280, 'W3', '7-3'),
  rank(2, 'BAL', 'Baltimore Orioles', 'AL East', 39, 27, 340, 300, 'L1', '6-4'),
  rank(3, 'BOS', 'Boston Red Sox', 'AL East', 35, 31, 320, 315, 'W1', '5-5'),
  rank(4, 'TB', 'Tampa Bay Rays', 'AL East', 33, 33, 300, 305, 'L2', '4-6'),
  rank(5, 'TOR', 'Toronto Blue Jays', 'AL East', 31, 35, 290, 320, 'L1', '4-6'),
  // AL Central
  rank(1, 'CLE', 'Cleveland Guardians', 'AL Central', 42, 24, 330, 270, 'W4', '8-2'),
  rank(2, 'KC', 'Kansas City Royals', 'AL Central', 38, 28, 325, 290, 'W2', '6-4'),
  rank(3, 'MIN', 'Minnesota Twins', 'AL Central', 36, 30, 315, 300, 'L1', '5-5'),
  rank(4, 'DET', 'Detroit Tigers', 'AL Central', 33, 33, 295, 305, 'W1', '5-5'),
  rank(5, 'CWS', 'Chicago White Sox', 'AL Central', 21, 45, 240, 360, 'L6', '2-8'),
  // AL West
  rank(1, 'HOU', 'Houston Astros', 'AL West', 40, 26, 350, 285, 'W2', '7-3'),
  rank(2, 'SEA', 'Seattle Mariners', 'AL West', 38, 28, 320, 290, 'W1', '6-4'),
  rank(3, 'TEX', 'Texas Rangers', 'AL West', 34, 32, 310, 308, 'L2', '5-5'),
  rank(4, 'LAA', 'Los Angeles Angels', 'AL West', 29, 37, 280, 330, 'L3', '3-7'),
  rank(5, 'OAK', 'Oakland Athletics', 'AL West', 26, 40, 260, 350, 'L1', '4-6'),
  // NL East
  rank(1, 'PHI', 'Philadelphia Phillies', 'NL East', 44, 22, 370, 270, 'W5', '8-2'),
  rank(2, 'ATL', 'Atlanta Braves', 'NL East', 39, 27, 355, 290, 'W1', '6-4'),
  rank(3, 'NYM', 'New York Mets', 'NL East', 34, 32, 315, 310, 'L1', '5-5'),
  rank(4, 'WSH', 'Washington Nationals', 'NL East', 31, 35, 295, 325, 'W2', '5-5'),
  rank(5, 'MIA', 'Miami Marlins', 'NL East', 25, 41, 255, 350, 'L4', '3-7'),
  // NL Central
  rank(1, 'MIL', 'Milwaukee Brewers', 'NL Central', 39, 27, 335, 295, 'W2', '6-4'),
  rank(2, 'STL', 'St. Louis Cardinals', 'NL Central', 36, 30, 320, 305, 'W1', '6-4'),
  rank(3, 'CHC', 'Chicago Cubs', 'NL Central', 35, 31, 318, 308, 'L1', '5-5'),
  rank(4, 'CIN', 'Cincinnati Reds', 'NL Central', 33, 33, 300, 305, 'W1', '5-5'),
  rank(5, 'PIT', 'Pittsburgh Pirates', 'NL Central', 31, 35, 285, 315, 'L2', '4-6'),
  // NL West
  rank(1, 'LAD', 'Los Angeles Dodgers', 'NL West', 45, 21, 385, 265, 'W6', '9-1'),
  rank(2, 'SD', 'San Diego Padres', 'NL West', 38, 28, 330, 295, 'W1', '6-4'),
  rank(3, 'ARI', 'Arizona Diamondbacks', 'NL West', 35, 31, 325, 315, 'L1', '5-5'),
  rank(4, 'SF', 'San Francisco Giants', 'NL West', 33, 33, 305, 308, 'L1', '5-5'),
  rank(5, 'COL', 'Colorado Rockies', 'NL West', 24, 42, 270, 380, 'L5', '2-8'),
];

function rank(
  r: number,
  team: string,
  teamName: string,
  division: string,
  wins: number,
  losses: number,
  runsScored: number,
  runsAllowed: number,
  streak: string,
  lastTen: string
): TeamRanking {
  const pct = (wins / (wins + losses)).toFixed(3).replace(/^0/, '');
  return {
    id: `rank-${team}`,
    rank: r,
    team,
    teamName,
    division,
    wins,
    losses,
    pct,
    gamesBack: r === 1 ? '-' : '',
    runsScored,
    runsAllowed,
    runDiff: runsScored - runsAllowed,
    streak,
    lastTen,
  };
}

// ─── Saved Edges (seed) ─────────────────────────────────────────────────────

export const mockSavedEdgesSeed: SavedEdge[] = [
  {
    id: 'edge-seed-1',
    propId: 'p-judge',
    player: 'Aaron Judge',
    prop: 'Home Runs',
    line: 0.5,
    direction: 'over',
    edge: 12.4,
    confidence: 'high',
    savedAt: new Date().toISOString(),
    notes: 'Wind blowing out at Yankee Stadium',
  },
  {
    id: 'edge-seed-2',
    propId: 'p-cole',
    player: 'Gerrit Cole',
    prop: 'Strikeouts (Pitcher)',
    line: 7.5,
    direction: 'over',
    edge: 6.8,
    confidence: 'medium',
    savedAt: new Date().toISOString(),
  },
];

// ─── Analytics ──────────────────────────────────────────────────────────────

export const mockAnalyticsData: AnalyticsData = {
  cards: [
    {
      id: 'card-1',
      label: 'Games Today',
      value: '15',
      change: '+2 vs yesterday',
      trend: 'up',
      description: 'Total MLB games scheduled today',
    },
    {
      id: 'card-2',
      label: 'Avg Over/Under',
      value: '8.7',
      change: '-0.3 vs season avg',
      trend: 'down',
      description: 'Average total runs line across all games',
    },
    {
      id: 'card-3',
      label: 'High-Edge Props',
      value: '24',
      change: '+6 vs yesterday',
      trend: 'up',
      description: 'Props with edge > 5%',
    },
    {
      id: 'card-4',
      label: 'Weather Alerts',
      value: '3',
      change: 'Wind > 15mph',
      trend: 'neutral',
      description: 'Games with significant weather impact',
    },
  ],
  barrelRate: [
    { name: 'Groundball', pct: 0.38 },
    { name: 'Line Drive', pct: 0.24 },
    { name: 'Fly Ball', pct: 0.29 },
    { name: 'Pop Up', pct: 0.09 },
  ],
  lineMovement: [
    { time: 'Open', over: 7.5, under: 7.5 },
    { time: '8am', over: 7.5, under: 7.5 },
    { time: '10am', over: 8.0, under: 7.5 },
    { time: '12pm', over: 8.0, under: 8.0 },
    { time: '2pm', over: 8.5, under: 8.0 },
    { time: '4pm', over: 8.5, under: 8.5 },
    { time: 'Live', over: 9.0, under: 8.5 },
  ],
  pitcherRadar: [
    { metric: 'K%', value: 32, league: 22 },
    { metric: 'BB%', value: 6, league: 8 },
    { metric: 'Whiff%', value: 31, league: 25 },
    { metric: 'Chase%', value: 34, league: 28 },
    { metric: 'Velo', value: 97, league: 93 },
    { metric: 'GB%', value: 48, league: 43 },
  ],
  wobaTrend: [
    { date: 'Apr', woba: 0.31 },
    { date: 'May', woba: 0.34 },
    { date: 'Jun', woba: 0.36 },
    { date: 'Jul', woba: 0.39 },
    { date: 'Aug', woba: 0.37 },
    { date: 'Sep', woba: 0.4 },
  ],
};
